Validador de CPF e testes associados
CalebeEmerick/Exercise01 pull request #3
Opened 2018-02-03 08:15 UTC by CalebeEmerick

2018-02-05 08:46 UTC, ubiratansoares requested changes

2018-02-05 08:46 UTC, ubiratansoares commented on Source/Exercise01Tests/CPFValidatorTests.swift
> +		let cpf = "144.130.507-62"
O CPF (assim como o CNPJ) é um pouquinho mais complexo do que os 11 dígitos!

Esse segue uma regra de formação que está documentada oficialmente em

http://www.consultaesic.cgu.gov.br/busca/dados/Lists/Pedido/Attachments/495242/RESPOSTA_PEDIDO_16853005945201692.pdf

e extra oficialmente em

http://www.geradorcpf.com/algoritmo_do_cpf.htm
http://www.fidelis.work/chega-de-gambeta-como-validar-cnpj-e-cpf-corretamente/

de maneira que a validação deve extrair propriedades de máscara de entrada (se aplicável) e validar a formação segundo os dígitos, numericamente.

Existem muitas implementações pela Web, principalmente em JS, dá uma olhadinha!

2018-02-05 18:08 UTC, CalebeEmerick commented on Source/Exercise01Tests/CPFValidatorTests.swift
> +		let cpf = "144.130.507-62"
Adicionada validação lógica 🎉

2018-02-06 13:03 UTC, ubiratansoares requested changes

2018-02-06 13:03 UTC, ubiratansoares commented on Source/Exercise01/SignUp/Model/CPFValidator.swift
> +			numbers[7] * 3 +
A gente não teria como extrair uma função que encapsula boa parte da lógica que trabalha com os digítos do CPF?

Repare que existe muita repetição entra o que é feito para computar o valor de `firstBlock` e `secondBlock`!

2018-02-06 13:07 UTC, merged

2018-02-06 13:09 UTC, CalebeEmerick commented on Source/Exercise01/SignUp/Model/CPFValidator.swift
> +			numbers[7] * 3 +
Está certo, vou refatorar.